apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ov0g7anru-go 
  janus-idp.io/tekton: ov0g7anru-go
  backstage.io/kubernetes-id: ov0g7anru-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ov0g7anru-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml