apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ov0g7anru-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ov0g7anru-go 
  name: ov0g7anru-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ov0g7anru-go 
